name: lfmPlan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.1.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test iOS
      run: xcodebuild test -project GithubActions.xcodeproj -scheme GithubActions clean build -testPlan LfmTestPlan -sdk iphoneos -destination "platform=iOS Simulator,OS=17.5,name=iPhone SE (3rd generation)" CODE_SIGNING_ALLOWED=No