require 'pathname'

default_platform(:ios)

platform :ios do
  desc "Run tests including snapshots"
  lane :test do
    # Change to project root directory
    Dir.chdir("..") do  # Add this to move up one directory
      FileUtils.rm_rf("Tests/ReferenceImages")
      
      sh("git clone https://x-access-token:#{ENV['REPO_TOKEN']}@github.com/#{ENV['SNAPSHOT_REPO']}.git snapshots_repo")
      
      FileUtils.mkdir_p("Tests/ReferenceImages")
      
      if Dir.exist?("snapshots_repo/ReferenceImages")
        FileUtils.cp_r(Dir["snapshots_repo/ReferenceImages/."], "Tests/ReferenceImages/")
      end

      scan(
        scheme: "GithubActions",
        device: "iPhone SE (3rd generation)",
        clean: true,
        configuration: "Debug",
        derived_data_path: "DerivedData"
      )
    end
  end
end