name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '16.1'
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test iOS
      run: xcodebuild test -project GithubActions.xcodeproj -scheme GithubActions clean build -testPlan LfmTestPlan -destination "platform=iOS Simulator,OS=18.1,name=iPhone SE (3rd generation)" CODE_SIGNING_ALLOWED=No
